/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface Env --include-runtime false` (hash: 4cbb4a0a8aadb84f21a46310704c13dc)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
	}
	interface Env {
		UPLOADS: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		PUBLIC_UPLOADS_URL: "https://uploads.agent-notion.tancn.dev";
		APP_URL: "https://agent-notion.tancn.dev";
		DATABASE_URL: string;
		ELECTRIC_URL: string;
		BETTER_AUTH_SECRET: string;
		BETTER_AUTH_URL: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		VITE_SENTRY_DSN: string;
		VITE_SENTRY_ORG: string;
		VITE_SENTRY_PROJECT: string;
		SENTRY_AUTH_TOKEN: string;
		POLAR_ACCESS_TOKEN: string;
		POLAR_SUCCESS_URL: string;
		RESEND_API_KEY: string;
		ELECTRIC_SQL_CLOUD_SOURCE_ID: string;
		ELECTRIC_SQL_CLOUD_SOURCE_SECRET: string;
		BETTER_FORM_READ_WRITE_TOKEN: string;
		VITE_APP_NAME: string;
		VITE_APP_WEBSITE_URL: string;
		VITE_APP_DOCS_URL: string;
		VITE_APP_API_DOCS_URL: string;
		AI_PROVIDER: string;
		AI_API_KEY: string;
		AI_MODEL: string;
		VERCEL_TOKEN: string;
		VERCEL_PROJECT_ID: string;
		VERCEL_TEAM_ID: string;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "PUBLIC_UPLOADS_URL" | "APP_URL" | "DATABASE_URL" | "ELECTRIC_URL" | "BETTER_AUTH_SECRET" | "BETTER_AUTH_URL" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "VITE_SENTRY_DSN" | "VITE_SENTRY_ORG" | "VITE_SENTRY_PROJECT" | "SENTRY_AUTH_TOKEN" | "POLAR_ACCESS_TOKEN" | "POLAR_SUCCESS_URL" | "RESEND_API_KEY" | "ELECTRIC_SQL_CLOUD_SOURCE_ID" | "ELECTRIC_SQL_CLOUD_SOURCE_SECRET" | "BETTER_FORM_READ_WRITE_TOKEN" | "VITE_APP_NAME" | "VITE_APP_WEBSITE_URL" | "VITE_APP_DOCS_URL" | "VITE_APP_API_DOCS_URL" | "AI_PROVIDER" | "AI_API_KEY" | "AI_MODEL" | "VERCEL_TOKEN" | "VERCEL_PROJECT_ID" | "VERCEL_TEAM_ID">> {}
}
